<?php
$includes = [
    'rewrite-rules.php',
    'pre-posts.php',
    'render-products-categories.php',
    'render-products.php',
    'get-icon-helper.php'
];

foreach ($includes as $file) {
    require_once get_template_directory() . '/inc/' . $file;
};

/**
 * Organic Theme functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package Organic
 */


if (! function_exists('organic_theme_scripts')) :
    /**
     * Enqueue scripts and styles.
     */
    function organic_theme_scripts()
    {
        // Get the asset file data generated by wp-scripts.
        $asset_file = include get_template_directory() . '/build/index.asset.php';

        // --- Stylesheets ---

        // Enqueue Google Fonts
        wp_enqueue_style(
            'organic-google-fonts',
            'https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&family=Open+Sans:ital,wght@0,400;0,700;1,400;1,700&display=swap',
            array(),
            null
        );

        // Enqueue Swiper CSS from CDN
        wp_enqueue_style(
            'swiper-css',
            'https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css',
            array(),
            '9.0.0' // Version number for Swiper
        );

        // Enqueue Bootstrap CSS from CDN
        wp_enqueue_style(
            'bootstrap-css',
            'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css',
            array(),
            '5.3.0', // Version number for Bootstrap
            'all',
            array(
                'integrity'  => 'sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ',
                'crossorigin' => 'anonymous',
            )
        );

        // Enqueue local vendor CSS (pre-minified from your assets folder)
        wp_enqueue_style(
            'organic-vendor-css',
            get_template_directory_uri() . '/assets/css/vendor.css',
            array('bootstrap-css'), // Assuming vendor CSS depends on Bootstrap
            '1.0.0' // Theme version or asset version
        );

        // Enqueue the main stylesheet from the `build` folder.
        // This is the file generated by wp-scripts from your source code.
        wp_enqueue_style(
            'my-theme-style',
            get_template_directory_uri() . '/build/index.css',
            array('organic-vendor-css'), // Depends on your local vendor CSS
            $asset_file['version']
        );

        wp_enqueue_style(
            'my-theme-editor-style',
            get_template_directory_uri() . '/build/style-index.css',
            array('my-theme-style'), // Depends on your main theme style
            $asset_file['version']
        );



        // --- JavaScripts ---

        // Deregister WordPress's default jQuery to use your custom version
        wp_deregister_script('jquery');

        // Enqueue custom jQuery (from assets/js)
        wp_enqueue_script(
            'jquery-custom',
            get_template_directory_uri() . '/assets/js/jquery-1.11.0.min.js',
            array(), // No dependencies for jQuery itself
            '1.11.0', // Version number for your custom jQuery
            true // Load in footer
        );

        // Enqueue Swiper JS from CDN (depends on your custom jQuery)
        wp_enqueue_script(
            'swiper-js',
            'https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js',
            array('jquery-custom'),
            '9.0.0',
            true // Load in footer
        );

        // Enqueue Bootstrap JS from CDN (depends on your custom jQuery)
        wp_enqueue_script(
            'bootstrap-js',
            'https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js',
            array('jquery-custom'),
            '5.3.0',
            true // Load in footer
        );

        // Enqueue local plugins JS (pre-minified from assets/js, depends on custom jQuery and Bootstrap)
        wp_enqueue_script(
            'organic-plugins-js',
            get_template_directory_uri() . '/assets/js/plugins.js',
            array('jquery-custom', 'bootstrap-js'),
            '1.0.0',
            true // Load in footer
        );

        // Enqueue theme's main script from the `build` folder.
        // This file contains all your new JS and depends on your old scripts.
        wp_enqueue_script(
            'my-theme-script',
            get_template_directory_uri() . '/build/index.js',
            array('organic-plugins-js'), // All other dependencies should be included in your main script's dependencies.
            $asset_file['version'],
            true // Load in footer
        );
    }
endif;

add_action('wp_enqueue_scripts', 'organic_theme_scripts');
